# Generated by Django 6.1 on 2026-08-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(default='', max_length=50, verbose_name='contacto'),
        ),
    ]
