# Generated by Django 6.1 on 2026-08-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_cliente_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='Dni')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha_Alta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Coordinador',
                'verbose_name_plural': 'coordinadores',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('legajo', models.IntegerField(verbose_name='Legajo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'empleados',
            },
        ),
        migrations.DeleteModel(
            name='Coordinadores',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
    ]
