# Generated by Django 6.0.7 on 2026-08-29 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_coordinador_empleado_delete_coordinadores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_servicio', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='servicios.cliente')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_coordinador', to='servicios.coordinador')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_empleado', to='servicios.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='servicios.servicio')),
            ],
        ),
        migrations.DeleteModel(
            name='ReservasServicios',
        ),
    ]
