# Generated by Django 6.0.7 on 2026-08-31 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_reservaservicios_delete_reservasservicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservaservicios',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
