# Generated by Django 6.1 on 2026-09-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_reservaservicios_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.PositiveIntegerField(verbose_name='Meta de ventas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Objetivo de venta',
                'verbose_name_plural': 'Objetivos de venta',
            },
        ),
    ]
