# Generated by Django 6.0.7 on 2026-09-02 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_objetivoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivoventa',
            name='meta',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Meta de ventas'),
        ),
    ]
